# Generated by Django 3.0.3 on 2021-04-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Profession', models.CharField(max_length=50)),
                ('Salary', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Phone_Numbers', models.IntegerField(max_length=13)),
                ('First_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form_app.Profile')),
            ],
        ),
    ]
